config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  # resources :posts
  # resources :boards
  resources :comments

  resources :boards  do
	  resources :posts  do
	    resources :comments
	  end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
	has_many :posts
	validates :title,    length: { maximum: 100 } 
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	validates :title,    length: { maximum: 100 } 
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :board
	has_many :comments
	validates :title,    length: { maximum: 100 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    @board.update(board_params)
    if @board.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def index
    @boards = Board.all
    @new_posts = Post.last(5)
  end

  def show
    @board = Board.find(params[:id])
    @posts = @board.posts
  end

  def destroy
    @board = Board.find(params[:id])
    posts = Post.where(board_id: @board.id)
    comments = Comment.where(board_id: @board.id)
    comments.delete_all
    posts.delete_all
    @board.delete
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(
        :title,
        :detail
    )
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comments_params)
    @comment.post_id = params[:post_id]
    @comment.board_id = params[:board_id]

    if @comment.save
      redirect_to board_path(params[:board_id])
    else
      redirect_to root_path
    end

  end

  def edit
  end

  def update
  end

  def destroy
    @comment = Comment.find(params[:id])
    board_id = @comment.board_id
    @comment.delete
    redirect_to  board_path(board_id)
  end

  def index
  end

  def show
  end

    def comments_params
    params.require(:comment).permit(
        :title,
        :body,
        :board_id,
        :post_id
    )
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    @post.board_id = params[:board_id]

    if @post.save
      redirect_to board_path(params[:board_id])
    else
      redirect_to root_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @post = Post.find(params[:id])
    board_id = @post.board_id
    comments = Comment.where(post_id: @post.id)
    comments.delete_all
    @post.delete
    redirect_to board_path(board_id)

  end

  def index
  end

  def show
  end

  private

  def posts_params
    params.require(:post).permit(
        :title,
        :body,
        :board_id
    )
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/borads_helper.rb
module BoradsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/boards/edit.html.erb
<div class="row">
	<div class="col-lg-2"></div>
	<div class="col-lg-8 col-xs-12">
		<h1 style="text-align: center; font-weight: 800;">
			スレッドを編集する
		</h1>
		<%= form_for @board do |f| %>
		<b>スレッドタイトル(100文字以内)</b><br>
			<%= f.text_field :title %><br>
		<b>詳細</b><br>
			<%= f.text_area :detail %><br>
			<%=f.submit '編集を完了する', class: 'btn btn-primary btn-lg btn-block' %>
		<% end %>
	</div>
	<div class="col-lg-2"></div>
</div>

app/views/boards/index.html.erb
<div class="row padding_top">
	<div class="col-lg-4">
		<div style="text-align: center; font-weight: 900;font-size: 25px;">
			スレッド一覧
		</div>
		<% @boards.each do |b| %>
			<ul id="nav">
				<li><%=link_to "#{b.title}", board_path(b.id)  %></li>
			</ul>
		<% end %>
	</div>
	<div class="col-lg-8">
		<div class="row">
			<div class="col-lg-2"></div>
			<%= link_to "スレッドを新しく作成する", new_board_path, class: "btn btn-primary btn-lg" %>
			<div class="col-lg-8 col-xs-12 ">
				<h2 style="text-align: center;">最新の発言一覧</h2>
				<% @new_posts.each do |p| %>
				<div class="kakomi">
				<div style="text-align:right;"><%= p.board.title %>のスレッドの投稿<br></div>
					タイトル:<%= p.title %><br>
					<%= p.body %><br>
				</div>
				<% end %>
			</div>
			<div class="col-lg-2"></div>
		</div>
	</div>
</div>

app/views/boards/new.html.erb
<div class="row">
	<div class="col-lg-2"></div>
	<div class="col-lg-8 col-xs-12">
		<h1 style="text-align: center; font-weight: 800;">
			スレッドを新しく建てる
		</h1>
		<%= form_for @board do |f| %>
		<b>スレッドタイトル(100文字以内)</b><br>
			<%= f.text_field :title %><br>
		<b>詳細</b><br>
			<%= f.text_area :detail %><br>
			<%=f.submit 'スレッドを発行する', class: 'btn btn-primary btn-lg btn-block' %>
		<% end %>
	</div>
	<div class="col-lg-2"></div>
</div>

app/views/boards/show.html.erb
<div>
	<%= link_to "投稿する", new_board_post_path(board_id: params[:id]),class: "btn btn-primary btn-lg" %>
	<%= link_to "スレットを編集する" , edit_board_path(params[:id]),class: "btn btn-success btn-lg" %>
	<%= link_to "スレッド削除", board_path(params[:id]) ,method: :delete, class: "btn btn-danger btn-lg",data: { confirm: 'このスレッドを削除して本当によろしいですか？' }  %>
</div>
<hr>
<div class="row padding_top">
	<h2 style="text-align: center;"><%= @board.detail %></h2>
	<% @posts.each do |p| %>
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="kakomi">
		<b>タイトル: <%= p.title %></b><br>
		<%= p.body %><br>
		<div class="row">
			<div class="col-lg-1"></div>
			<div class="col-lg-10">
				<% p.comments.each do |c| %>
					<div class="kakomi_mini">
						<%= c.title %><br>
						<%= c.body %><br>
						<%= link_to "この返信を削除する", comment_path(c.id), method: :delete,data: { confirm: '本当に削除してよろしいですか？' }  %>
					</div>
				<% end %>
			</div>
			<div class="col-lg-1"></div>
		</div>
		<%= link_to "返信する",new_board_post_comment_path(board_id: params[:id], post_id: p.id), class: "btn btn-primary" %>
		<%= link_to "この発言を削除する",board_post_path(board_id: params[:id], id: p.id),method: :delete,  class: "btn btn-danger",data: { confirm: 'この発言を削除して本当によろしいですか？' } %>
		</div>
	</div>
	<div class="col-lg-2"></div>
	<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<div class="row">
	<div class="col-lg-2"></div>
	<div class="col-lg-8 col-xs-12 padding_top">
		タイトル: <%= @post.title %><br>
		<%= @post.body %>

		<hr>
		<%= form_for @comment, url: board_post_comments_path(board_id: params[:board_id], post_id: params[:post_id]) do |f| %>
			タイトル(100文字以内)<br>
			<%= f.text_field :title %><br>
			本文<br>
			<%= f.text_area :body %><br>
			<%=f.submit '返信する', class: 'btn btn-primary btn-lg btn-block' %>
		<% end %>
	</div>
	<div class="col-lg-2"></div>
</div>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light nav_left_padding">
  <a class="navbar-brand" style="font-weight: 800; font-size: 1.5em;" href="/">ホーム</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%=link_to  "スレッド作成", new_board_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AteamApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<div class="row">
	<div class="col-lg-2"></div>
	<div class="col-lg-8 col-xs-12">
		<h1 style="text-align: center; font-weight: 800;">
			新しく発言する
		</h1>
		<%= form_for @post, url: board_posts_path(board_id: params[:board_id]) do |f| %>
			<p>タイトル(100文字以内)</p>
			<%= f.text_field :title %>
			<p>本文</p>
			<%= f.text_area :body %>
			<%=f.submit '発言する', class: 'btn btn-primary btn-lg btn-block' %>
		<% end %>
	</div>
	<div class="col-lg-2"></div>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>